### ISSUE TITLE
Empty supp_dict (image_classification.py)

### ISSUE THREAD

**Issue by andreamigliorati** [yoshitomo-matsubara/sc2-benchmark#143] opened 2024-07-12 08:27 UTC
Hi, I want to perform image classification and train my own models, I added the train keys to the config file to do that. However I have a problem with the `train_one_epoch` method. When computing the loss (`loss = training_box(sample_batch, targets, supp_dict)`) I get an error which appears to be caused by an empty `supp_dict`.

```
File "/media/RAID/migliorati/coding_machines/sc2-benchmark-main/script/task/image_classification.py", line 209, in main
    train(teacher_model, student_model, dataset_dict, ckpt_file_path, device, device_ids, distributed, config, args)
  File "/media/RAID/migliorati/coding_machines/sc2-benchmark-main/script/task/image_classification.py", line 160, in train
    train_one_epoch(training_box, aux_module, bottleneck_updated, device, epoch, log_freq)
  File "/media/RAID/migliorati/coding_machines/sc2-benchmark-main/script/task/image_classification.py", line 73, in train_one_epoch
    loss = training_box(sample_batch, targets, supp_dict)
```
Before being called in `loss = training_box(sample_batch, targets, supp_dict)`, `supp_dict` is created here:

```
    for sample_batch, targets, supp_dict in \
            metric_logger.log_every(training_box.train_data_loader, log_freq, header):
        if isinstance(sample_batch, torch.Tensor):
            sample_batch = sample_batch.to(device)

        if isinstance(targets, torch.Tensor):
            targets = targets.to(device)
```
which in my case gives an empty `supp_dict`, and therefore a missing key (`KeyError: 'backbone.bottleneck_layer'`). I am launching my training with `bash script/neural_input_compression/ilsvrc2012-image_classification.sh factorized_prior-resnet50 8`, and as mentioned I created a train key in the config file so I am not sure what I'm doing wrong. Thanks in advance!

**Comment by yoshitomo-matsubara** [comment] 2024-07-12 15:12
Please read https://github.com/yoshitomo-matsubara/sc2-benchmark?tab=readme-ov-file#issues--questions--requests and use [Discussions](https://github.com/yoshitomo-matsubara/sc2-benchmark/discussions) instead

Closing this as it's not a bug.

**Closed by yoshitomo-matsubara** 2024-07-12 15:12 UTC
